//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExemploPos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atividade
    {
        public Atividade()
        {
            this.Classificacao = new HashSet<Classificacao>();
        }
    
        public int Codigo { get; set; }
        public string Descricao { get; set; }
        public System.DateTime DataInicio { get; set; }
        public Nullable<System.DateTime> DataFim { get; set; }
        public int CodigoFuncionario { get; set; }
        public short CodigoStatus { get; set; }
        public string EmailSolicitante { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
        public virtual Solicitante Solicitante { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<Classificacao> Classificacao { get; set; }
    }
}
