//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExemploPos.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    internal partial class HelpDeskEntities : DbContext
    {
        internal HelpDeskEntities()
            : base("name=HelpDeskEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Atividade> Atividade { get; set; }
        public DbSet<Classificacao> Classificacao { get; set; }
        public DbSet<Funcionario> Funcionario { get; set; }
        public DbSet<Solicitante> Solicitante { get; set; }
        public DbSet<Status> Status { get; set; }
    }
}
