//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExemploPos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Atividade = new HashSet<Atividade>();
        }
    
        public short Codigo { get; set; }
        public string Descricao { get; set; }
        public string Ativo { get; set; }
    
        public virtual ICollection<Atividade> Atividade { get; set; }
    }
}
