/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package CamadaApresentacao;

import CamadaLogica.BancoDados;
import java.util.Date;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Victor
 */
public class relVendasPeriodo extends javax.swing.JFrame {

    /**
     * Creates new form relVendasPeriodo
     */
    public relVendasPeriodo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGerar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtInicio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFim = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGerar.setText("Gerar");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGerar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("(dd-mm-yyyy) Início: ");
        jPanel2.add(jLabel1);

        txtInicio.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel2.add(txtInicio);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Fim:");
        jPanel2.add(jLabel2);

        txtFim.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel2.add(txtFim);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
         BancoDados banco = new BancoDados();
try
{
    DateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
Date inicio = formatter.parse(txtInicio.getText());
Date fim = formatter.parse(txtFim.getText());

  String nome = "P";
  Map parameters = new HashMap();
  parameters.put("dtinicio", inicio);
  parameters.put("dtinicio", fim);
  
  //

  
  String jasperPrint = 
     JasperFillManager.fillReportToFile("relatorios/relVendasPeriodo.jasper", 
     parameters, banco.abrirConexao());
  JasperViewer viewer = new JasperViewer(jasperPrint, false, false);
  viewer.setExtendedState(JasperViewer.MAXIMIZED_BOTH);//maximizado
  viewer.setTitle("Relatório de Vendas/Clientes por Período");//titulo do relatório
  viewer.setVisible(true);
} catch (JRException erro)
{
  erro.printStackTrace();
}       catch (ParseException ex) {
            Logger.getLogger(relVendasPeriodo.class.getName()).log(Level.SEVERE, null, ex);
        }
banco.fecharConexao();
    }//GEN-LAST:event_btnGerarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtFim;
    private javax.swing.JTextField txtInicio;
    // End of variables declaration//GEN-END:variables
}
