/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package CamadaApresentacao;

import CamadaLogica.BancoDados;
import CamadaNegocio.Funcionarios;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import javax.swing.JComboBox;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Victor
 */
public class relVendasFuncionarios extends javax.swing.JFrame {

    private Funcionarios f = new Funcionarios();
    /**
     * Creates new form relVendasFuncionarios
     */
    public relVendasFuncionarios(java.awt.Frame parent, boolean modal) throws Exception {
        initComponents();
        carregaFuncionarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGerar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbFuncionarios = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGerar.setText("Gerar");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGerar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Funcionário:");
        jPanel2.add(jLabel1);

        cbFuncionarios.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbFuncionarios.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel2.add(cbFuncionarios);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void carregaFuncionarios() throws Exception{  
            cbFuncionarios.removeAllItems();
            List<Funcionarios> l = f.listarFuncionarios();
           
      
        Iterator<Funcionarios> it = l.iterator();  
        while(it.hasNext()){  
            Funcionarios e = it.next();  
            String nome = e.getFis_nome();
            String cod = String.valueOf(e.getFis_codigo());
             cbFuncionarios.addItem(cod+"-"+nome); 
        }  
      
    }  
    
    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        BancoDados banco = new BancoDados();
try
{
  String cod[] = cbFuncionarios.getSelectedItem().toString().split("-");
  String nome = "P";
  Map parameters = new HashMap();
  parameters.put("func_codigo",cod[0] );

  String jasperPrint = 
     JasperFillManager.fillReportToFile("relatorios/relVendasFuncionarios.jasper", 
     parameters, banco.abrirConexao());
  JasperViewer viewer = new JasperViewer(jasperPrint, false, false);
  viewer.setExtendedState(JasperViewer.MAXIMIZED_BOTH);//maximizado
  viewer.setTitle("Relatório de Vendas Funcionários");//titulo do relatório
  viewer.setVisible(true);
} catch (JRException erro)
{
  erro.printStackTrace();
}
banco.fecharConexao();

    }//GEN-LAST:event_btnGerarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar;
    private javax.swing.JComboBox cbFuncionarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
