package CamadaApresentacao;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */





import CamadaNegocio.Clientes;
import CamadaNegocio.Funcionarios;
import CamadaNegocio.Produtos;
import CamadaNegocio.Vendas_;
import CamadaNegocio.Vendas_produtos; 
import java.sql.Date; 
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Victor
 */
public class Vendas extends javax.swing.JDialog {
    
    Produtos prod = new Produtos(); 
    Clientes cli = new Clientes();
    Funcionarios func = new Funcionarios(); 
    Vendas_ vend = new Vendas_(); 
    Vendas_produtos itens = new Vendas_produtos();
    
    
    public Vendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Date data = new Date(System.currentTimeMillis());
        txtData.setText(data.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTotalAcumulado = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtQtd = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnLocProduto = new javax.swing.JButton();
        bntAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tVenda = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnFinaliza = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        btnLocCliente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtVendedor = new javax.swing.JTextField();
        btnLocVendedor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Venda");
        setMaximumSize(new java.awt.Dimension(679, 500));
        setMinimumSize(new java.awt.Dimension(679, 500));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Total Acumulado");

        txtTotalAcumulado.setEditable(false);
        txtTotalAcumulado.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtTotalAcumulado.setForeground(new java.awt.Color(255, 0, 0));
        txtTotalAcumulado.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtTotalAcumulado, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalAcumulado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Itens"));
        jPanel2.setMinimumSize(new java.awt.Dimension(674, 572));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setText("Produto");

        txtProduto.setEditable(false);

        txtValor.setEditable(false);

        jLabel11.setText("Valor");

        txtQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdActionPerformed(evt);
            }
        });
        txtQtd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQtdFocusLost(evt);
            }
        });
        txtQtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQtdKeyTyped(evt);
            }
        });

        jLabel12.setText("Qtd.");

        txtTotal.setEditable(false);

        jLabel13.setText("Total");

        btnLocProduto.setText("Localizar");
        btnLocProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocProdutoActionPerformed(evt);
            }
        });

        bntAdd.setText("+");
        bntAdd.setContentAreaFilled(false);
        bntAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bntAdd))))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLocProduto))
                        .addComponent(txtProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(btnLocProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 300));

        tVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Seq", "Produto", "Pr. Venda", "Qtd.", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tVenda);
        if (tVenda.getColumnModel().getColumnCount() > 0) {
            tVenda.getColumnModel().getColumn(0).setResizable(false);
            tVenda.getColumnModel().getColumn(1).setResizable(false);
            tVenda.getColumnModel().getColumn(2).setResizable(false);
            tVenda.getColumnModel().getColumn(3).setResizable(false);
            tVenda.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnFinaliza.setText("Finalizar");
        btnFinaliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizaActionPerformed(evt);
            }
        });
        jPanel5.add(btnFinaliza);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel5.add(btnSair);

        jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Cód.:");
        jPanel6.add(jLabel2);

        txtCodigo.setEditable(false);
        txtCodigo.setPreferredSize(new java.awt.Dimension(60, 20));
        jPanel6.add(txtCodigo);

        jLabel3.setText("Data:");
        jPanel6.add(jLabel3);

        txtData.setEditable(false);
        txtData.setPreferredSize(new java.awt.Dimension(60, 20));
        jPanel6.add(txtData);

        jLabel4.setText("Cliente:");
        jPanel6.add(jLabel4);

        txtCliente.setEditable(false);
        txtCliente.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel6.add(txtCliente);

        btnLocCliente.setText("Localizar");
        btnLocCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocClienteActionPerformed(evt);
            }
        });
        jPanel6.add(btnLocCliente);

        jLabel5.setText("Vendedor:");
        jPanel6.add(jLabel5);

        txtVendedor.setEditable(false);
        txtVendedor.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel6.add(txtVendedor);

        btnLocVendedor.setText("Localizar");
        btnLocVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocVendedorActionPerformed(evt);
            }
        });
        jPanel6.add(btnLocVendedor);

        jPanel4.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLocProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocProdutoActionPerformed
        ConsultaPadrao consProd = new ConsultaPadrao(null, true);
        //Configurando a Consulta
        String[] vet = new String[2];
        vet[0] = "Código";
        vet[1] = "Nome";
        //configuraOpcoes(string[] vetOpcoes, int tl, int posDefault, String tabela)
        consProd.configuraOpcoes(vet, 2, 1, "Produtos");
        //........................

        consProd.setVisible(true);
        if (consProd.getCodigo() != 0)
        {
            PreencheCampos(consProd.getCodigo());
            consProd.dispose();
          
        }
        else
        {
            
            consProd.dispose();
            
        } 
    }//GEN-LAST:event_btnLocProdutoActionPerformed

    private void txtQtdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQtdFocusLost
                
        int qtde = Integer.parseInt(txtQtd.getText());     
        
        if(!ChecaEstoque(qtde))
        {
            JOptionPane.showMessageDialog(rootPane, "Estoque esgotadado!!!"); 
            txtQtd.setText("");
            txtTotal.setText("");
           // txtQtd.setFocusable(true);
            txtQtd.requestFocus();
        }
        else
        {
             txtTotal.setText(String.valueOf(prod.getProd_valor() * qtde));
             
             
             
        }
            
        
    }//GEN-LAST:event_txtQtdFocusLost

    private void txtQtdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdKeyTyped
        
       
        
        
    }//GEN-LAST:event_txtQtdKeyTyped

    private void txtQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdActionPerformed
        // JOptionPane.showConfirmDialog(rootPane, "Estoque esgotadado!!!");
    }//GEN-LAST:event_txtQtdActionPerformed

    private void bntAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAddActionPerformed
         
           
           
          Double totAcumulado, totTotal; 
        
          totAcumulado = Double.parseDouble(0 + txtTotalAcumulado.getText());
          totTotal = Double.parseDouble(txtTotal.getText());             
          
          int qtde = Integer.parseInt(txtQtd.getText());
          
          DefaultTableModel model=(DefaultTableModel)tVenda.getModel();
          
          int flag = 0; 
          
          for(int i=0; i < model.getRowCount(); i++)
          {
              if(Integer.parseInt(model.getValueAt(i, 0)+"") == prod.getProd_codigo())
              {
                  if(!ChecaEstoque(qtde +  Integer.parseInt(model.getValueAt(i, 3).toString())))
                        JOptionPane.showMessageDialog(rootPane, "Quantidade indisponivel");
                  else
                  {
                      model.setValueAt(qtde +  Integer.parseInt(model.getValueAt(i, 3).toString()), i, 3);
                      JOptionPane.showMessageDialog(rootPane, "Produto Atualizado");
                      txtTotalAcumulado.setText(String.valueOf(totAcumulado + totTotal));                      
                      model.setValueAt(Double.parseDouble(model.getValueAt(i, 4).toString()) + (qtde * prod.getProd_valor()) , i, 4);
                  }                  
                  flag = 1;   
              }      
          }
          
          
          
          
          if(flag == 0)
          {
            model.addRow(new String[]{
                prod.getProd_codigo()+"",
                prod.getProd_nome(),
                txtValor.getText(), 
                txtQtd.getText(), 
                txtTotal.getText()}); 

            JOptionPane.showMessageDialog(rootPane, "Produto Adicionado com sucesso");
            txtTotalAcumulado.setText(String.valueOf(totAcumulado + totTotal));
          }         
          txtQtd.setText("");
          txtValor.setText("");
          txtTotal.setText("");
          txtProduto.setText("");
    }//GEN-LAST:event_bntAddActionPerformed

    private void btnLocClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocClienteActionPerformed
          ConsultaPadrao consProd = new ConsultaPadrao(null, true);
        //Configurando a Consulta
        String[] vet = new String[2];
        vet[0] = "Código";
        vet[1] = "Nome";
        //configuraOpcoes(string[] vetOpcoes, int tl, int posDefault, String tabela)
        consProd.configuraOpcoes(vet, 2, 1, "Clientes");
        //........................

        consProd.setVisible(true);
        if (consProd.getCodigo() != 0)
        {
           // PreencheCampos(consProd.getCodigo());
            
            cli.setCli_codigo(consProd.getCodigo());
             if (cli.buscarPorCodigo())
            {
             txtCliente.setText(cli.getFis_nome());
            }
           
            
            consProd.dispose();
          
        }
        else
        {
            
            consProd.dispose();
            
        } 
    }//GEN-LAST:event_btnLocClienteActionPerformed

    private void btnFinalizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizaActionPerformed
       
        Date data = new Date(System.currentTimeMillis());
        
        vend.setCli_codigo(cli.getCli_codigo());
        vend.setFunc_codigo(func.getFunc_codigo());
        vend.setVend_data(null);
        vend.setVend_valor_total(Double.parseDouble(txtTotalAcumulado.getText()));
        
         
         
         DefaultTableModel model=(DefaultTableModel)tVenda.getModel();
         Vendas_produtos [] itens = new Vendas_produtos[model.getRowCount()];
         int cont = 0 ; 
         
         
         
         
         for(int i=0; i < model.getRowCount(); i++)
         {
               itens[cont++] = new Vendas_produtos(vend.getVend_codigo(),
                       Integer.parseInt(model.getValueAt(i, 0).toString()),
                       Integer.parseInt(model.getValueAt(i, 3).toString()), 
                       Double.parseDouble(model.getValueAt(i, 2).toString()));
              // cont++; 
         }
         vend.setVp(itens);
         
         
         if(vend.EfetuarVenda()) 
            JOptionPane.showMessageDialog(rootPane, "Venda Efetuada com sucesso!!");
         else
            JOptionPane.showMessageDialog(rootPane, "erro ao efetuar a venda !");
         
         
         
         model.setNumRows(0);
         txtTotalAcumulado.setText("");
         txtVendedor.setText("");
         txtCliente.setText("");
       
        
    }//GEN-LAST:event_btnFinalizaActionPerformed

    private void btnLocVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocVendedorActionPerformed
       ConsultaPadrao consProd = new ConsultaPadrao(null, true);
        //Configurando a Consulta
        String[] vet = new String[2];
        vet[0] = "Código";
        vet[1] = "Nome";
        //configuraOpcoes(string[] vetOpcoes, int tl, int posDefault, String tabela)
        consProd.configuraOpcoes(vet, 2, 1, "Funcionarios");
        //........................

        consProd.setVisible(true);
        if (consProd.getCodigo() != 0)
        {
           // PreencheCampos(consProd.getCodigo());
            
            func.setFunc_codigo(consProd.getCodigo());
             if (func.buscarPorCodigo())
            {
                txtVendedor.setText(func.getFis_nome());
            }
             
            consProd.dispose();
          
        }
        else
        {
            
            consProd.dispose();
            
        } 
    }//GEN-LAST:event_btnLocVendedorActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    public void PreencheCampos(int codigo)
    {       
        prod.setProd_codigo(codigo);
        prod.buscarPorCodigo(); 
        
        txtProduto.setText(prod.getProd_nome());
        txtValor.setText(String.valueOf(prod.getProd_valor()));      
        
    }
    
    public boolean ChecaEstoque(int qtde)
    {
        if(prod.getProd_estoque() >= qtde)
          return true; 
        else
          return false; 
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAdd;
    private javax.swing.JButton btnFinaliza;
    private javax.swing.JButton btnLocCliente;
    private javax.swing.JButton btnLocProduto;
    private javax.swing.JButton btnLocVendedor;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tVenda;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQtd;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalAcumulado;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtVendedor;
    // End of variables declaration//GEN-END:variables
}
